### ISSUE TITLE
q fails to compile with VS 2017 15.6.2

### ISSUE THREAD

**Issue by nholthaus** [grantila/q#19]
Compilation fails with the following error:

```
C:\dev\q\libs\q\include\q\promise\impl\rest.hpp(141): error C2244: 'q::detail::generic_promise<B,T...>::forward': unable to match function definition to an existing declaration
  C:\dev\q\libs\q\include\q/promise/impl/rest.hpp(140): note: see declaration of 'q::detail::generic_promise<B,T...>::forward'
  C:\dev\q\libs\q\include\q/promise/impl/rest.hpp(141): note: definition
  C:\dev\q\libs\q\include\q/promise/impl/rest.hpp(141): note: 'std::enable_if<std::is_void<_V>::value&&q::detail::generic_promise<B,T...>::argument_types::empty::value,q::promise<U...>>::type q::detail::generic_promise<B,T...>::forward(U &&...)'
  C:\dev\q\libs\q\include\q/promise/impl/rest.hpp(141): note: existing declarations
  C:\dev\q\libs\q\include\q/promise/impl/rest.hpp(141): note: 'std::enable_if<std::is_void<_V>::value&&q::arguments<To...>::empty::value,q::promise<U...>>::type q::detail::generic_promise<B,T...>::forward(U &&...)'
```

It looks to me like a bug with the compilers namespace resolution, but I'll submit a small PR which fixes the issue.

**Comment by grantila** [comment]
How utterly crazy, but the PR looks good, thanks!
